In [5]:
df_path = "/home/drfrbc/Neural-Modeling/scripts/2025-03-23-08-10-Basal_density_1035/Rates_by_RhythDep_AcrossSeeds/spike_rate_df.csv"

In [6]:
import pandas as pd

In [ ]:
stats = pd.read_csv(df_path)
stats

,Unnamed: 0,distal_rhyth_depth,perisomatic_rhyth_depth,Segment_Type,Total_NMDA_Spikes_mean,Total_NMDA_Spikes_std,Total_NA_Spikes_mean,Total_NA_Spikes_std,Total_CA_Spikes_mean,Total_CA_Spikes_std,soma_firing_rate_mean,soma_firing_rate_std
0,0,0.000,0.000,apic,6231.86,1019.193987,10121.48,2209.028747,257.78,86.384183,1.933333,2.289105
1,1,0.000,0.000,dend,6774.90,1182.616859,9463.10,2761.606647,0.00,0.000000,1.933333,2.289105
2,2,0.005,0.005,apic,6201.16,1019.610054,10324.34,2002.023498,262.02,91.360259,2.046667,2.086411
3,3,0.005,0.005,dend,6786.34,1169.673704,9449.18,2677.486007,0.00,0.000000,2.046667,2.086411
4,4,0.010,0.010,apic,6276.10,1024.164035,9985.92,1948.830940,268.74,68.909927,2.400000,2.364788
5,5,0.010,0.010,dend,6783.50,1145.945298,9425.04,2634.369844,0.00,0.000000,2.400000,2.364788
6,6,0.015,0.015,apic,6338.14,1054.905902,9972.52,2053.576120,293.96,76.629126,3.293333,2.778929
7,7,0.015,0.015,dend,6794.04,1145.062716,9355.32,2645.040071,0.00,0.000000,3.293333,2.778929

In [15]:
for spike_type in ['CA', 'NMDA', 'NA']:
    stats[f'Total_{spike_type}_Spikes_CV'] = stats[f'Total_{spike_type}_Spikes_std']/stats[f'Total_{spike_type}_Spikes_mean']
    stats[f'Total_{spike_type}_Spikes_FF'] = (stats[f'Total_{spike_type}_Spikes_std']**2)/stats[f'Total_{spike_type}_Spikes_mean']

stats[f'soma_firing_rate_CV'] = stats[f'soma_firing_rate_std']/stats[f'soma_firing_rate_mean']
stats[f'soma_firing_rate_FF'] = (stats[f'soma_firing_rate_std']**2)/stats[f'soma_firing_rate_mean']

In [16]:
stats

,Unnamed: 0,distal_rhyth_depth,perisomatic_rhyth_depth,Segment_Type,Total_NMDA_Spikes_mean,Total_NMDA_Spikes_std,Total_NA_Spikes_mean,Total_NA_Spikes_std,Total_CA_Spikes_mean,Total_CA_Spikes_std,soma_firing_rate_mean,soma_firing_rate_std,Total_CA_Spikes_CV,Total_CA_Spikes_FF,Total_NMDA_Spikes_CV,Total_NMDA_Spikes_FF,Total_NA_Spikes_CV,Total_NA_Spikes_FF,soma_firing_rate_CV,soma_firing_rate_FF
0,0,0.000,0.000,apic,6231.86,1019.193987,10121.48,2209.028747,257.78,86.384183,1.933333,2.289105,0.335108,28.948045,0.163546,166.684807,0.218252,482.123959,1.184020,2.710345
1,1,0.000,0.000,dend,6774.90,1182.616859,9463.10,2761.606647,0.00,0.000000,1.933333,2.289105,NaN,NaN,0.174559,206.435908,0.291829,805.916801,1.184020,2.710345
2,2,0.005,0.005,apic,6201.16,1019.610054,10324.34,2002.023498,262.02,91.360259,2.046667,2.086411,0.348677,31.855190,0.164422,167.646805,0.193913,388.218335,1.019419,2.126927
3,3,0.005,0.005,dend,6786.34,1169.673704,9449.18,2677.486007,0.00,0.000000,2.046667,2.086411,NaN,NaN,0.172357,201.601537,0.283356,758.682903,1.019419,2.126927
4,4,0.010,0.010,apic,6276.10,1024.164035,9985.92,1948.830940,268.74,68.909927,2.400000,2.364788,0.256419,17.669785,0.163185,167.127989,0.195158,380.329707,0.985328,2.330093
5,5,0.010,0.010,dend,6783.50,1145.945298,9425.04,2634.369844,0.00,0.000000,2.400000,2.364788,NaN,NaN,0.168931,193.585999,0.279508,736.326262,0.985328,2.330093
6,6,0.015,0.015,apic,6338.14,1054.905902,9972.52,2053.576120,293.96,76.629126,3.293333,2.778929,0.260679,19.975585,0.166438,175.576188,0.205923,422.879561,0.843804,2.344872
7,7,0.015,0.015,dend,6794.04,1145.062716,9355.32,2645.040071,0.00,0.000000,3.293333,2.778929,NaN,NaN,0.168539,192.988064,0.282731,747.835133,0.843804,2.344872

In [ ]:
stats.to_csv('Spike_stats_for_rhyth_sim_30sec.csv')

Old below

In [8]:
rhythmicity = (stats.distal_rhyth_depth[1], stats.perisomatic_rhyth_depth[1])
rhythmicity

KeyError: 1

In [11]:
stats["Total_CA_Spikes.1"]

0          fano_factor
1    37.58489795918368
2                  NaN
Name: Total_CA_Spikes.1, dtype: object

In [12]:
fanofactors = {
    stats["Total_CA_Spikes.1"][1],
}